# Generated by Django 4.2.5 on 2023-09-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_adminreg_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
